Document: hellopsl1
Title: Debian hellopsl1 Manual
Author: <insert document author here>
Abstract: This manual describes what hellopsl1 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hellopsl1/hellopsl1.sgml.gz

Format: postscript
Files: /usr/share/doc/hellopsl1/hellopsl1.ps.gz

Format: text
Files: /usr/share/doc/hellopsl1/hellopsl1.text.gz

Format: HTML
Index: /usr/share/doc/hellopsl1/html/index.html
Files: /usr/share/doc/hellopsl1/html/*.html
